# Generated by Django 5.1.6 on 2025-12-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('last_online', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_level', models.FloatField(default=25)),
                ('danger_level', models.FloatField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammonia_level', models.FloatField(help_text='Kadar amonia dalam ppm')),
                ('location', models.CharField(default='Toilet Lab Kimia A', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('MQTT', 'MQTT'), ('API', 'API')], default='MQTT', max_length=50)),
                ('status', models.CharField(choices=[('safe', 'Safe'), ('warning', 'Warning'), ('danger', 'Danger')], default='safe', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_97dc13_idx'), models.Index(fields=['location', '-timestamp'], name='monitoring__locatio_671635_idx')],
            },
        ),
    ]
