# Generated by Django 5.1.6 on 2025-12-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_point', models.FloatField(default=0, help_text='Zero point calibration value')),
                ('offset', models.FloatField(default=0, help_text='Offset adjustment untuk koreksi pembacaan')),
                ('last_calibration', models.DateTimeField(blank=True, help_text='Kapan terakhir dikalibrasi', null=True)),
                ('calibration_notes', models.TextField(blank=True, help_text='Catatan kalibrasi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='thresholdsetting',
            name='danger_level',
            field=models.FloatField(default=400),
        ),
        migrations.AlterField(
            model_name='thresholdsetting',
            name='warning_level',
            field=models.FloatField(default=350),
        ),
    ]
