# Generated by Django 5.1.6 on 2025-12-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_calibrationsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('MQTT_CONNECT', 'MQTT Connected'), ('MQTT_DISCONNECT', 'MQTT Disconnected'), ('SENSOR_ONLINE', 'Sensor Online'), ('SENSOR_OFFLINE', 'Sensor Offline'), ('THRESHOLD_CHANGED', 'Threshold Changed'), ('CALIBRATION_PERFORMED', 'Calibration Performed'), ('DATA_EXPORTED', 'Data Exported'), ('SYSTEM_ERROR', 'System Error'), ('SYSTEM_INFO', 'System Information')], max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('description', models.TextField()),
                ('details', models.JSONField(blank=True, help_text='Additional JSON data', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='monitoring__timesta_cac7c3_idx'), models.Index(fields=['event_type', '-timestamp'], name='monitoring__event_t_76ee9c_idx'), models.Index(fields=['severity', '-timestamp'], name='monitoring__severit_bc82d0_idx')],
            },
        ),
    ]
